version: '3.8'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-spark:latest
    env_file:
      - .env
    environment:
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8085
    ports:
      - "8085:8080"
    networks:
      - ndsnet
    command: "airflow webserver"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-spark:latest
    env_file:
      - .env
    networks:
      - ndsnet
    command: "airflow scheduler"

  triggerer:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-spark:latest
    env_file:
      - .env
    networks:
      - ndsnet
    command: "airflow triggerer"

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    env_file:
      - .env
    ports:
      - "8082:8080"  # Spark Web UI
      - "7077:7077"  # Spark Cluster Communication
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./conf/spark-defaults.conf:/spark/conf/spark-defaults.conf
    networks:
      - ndsnet

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker
    env_file:
      - .env
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Worker UI
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./conf/spark-defaults.conf:/spark/conf/spark-defaults.conf
    networks:
      - ndsnet

  metabase:
    image: metabase/metabase:v0.50.4
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./include/data/metabase:/metabase-data
    networks:
      - ndsnet

  docker-proxy:
    image: alpine/socat
    command: "socat TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock"
    ports:
      - "2376:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ndsnet

networks:
  ndsnet:
    driver: bridge
